name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Check Flutter version
        run: flutter --version

      - name: Create dummy .env file
        run: echo . > .env

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/latest
          rm cmdline-tools.zip
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          echo 'export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"' >> $GITHUB_ENV
          sdkmanager --update
      
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install dependencies
        run: flutter pub get

      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
